// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avkbfpzmqgrffhdnfewv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2a2JmcHptcWdyZmZoZG5mZXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjM2MjgsImV4cCI6MjA2MjA5OTYyOH0.LSsW8XuhqrnJK3etsHqbPir7BIwXvxZnY6jenvUSiQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);